@extends('adminLTE.layout')

@push('title')
Form Customer
@endpush

@push('page-name')
Form Customer
@endpush

@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="card card-primary">
      <!-- form start -->
      <form role="form" method="POST" action="{{ route($resource.'.store') }}" >
        @csrf

        <input type="hidden" name="id" value="{{isset($data) ? $data->id:''}}" />
        
        <div class="card-body">
          <h4>Data Customer</h4>
          <div class="row">

            <!-- Customer Code -->
            <div class="form-group col-md-12">
              <label for="customer_code">Customer Code <span class="text-danger">*</span></label>
              <input readonly autocomplete="off" name="customer_code" type="text" class="form-control" id="customer_code" placeholder="Generated By System" value="{{isset($data) ? $data->customer_code:''}}">
            </div>
            
            <!-- Name -->
            <div class="form-group col-md-6">
              <label for="name">Name <span class="text-danger">*</span></label>
              <input autocomplete="off" name="name" type="text" class="form-control" id="name" placeholder="" value="{{isset($data) ? $data->name:''}}">
            </div>
            <!-- Mobile Phone -->
            <div class="form-group col-md-6">
              <label for="mobile_phone">Mobile Phone <span class="text-danger">*</span></label>
              <input autocomplete="off" name="mobile_phone" type="text" class="form-control" id="mobile_phone" placeholder="" value="{{isset($data) ? $data->mobile_phone:''}}">
            </div>
            

            <!-- Address -->
            <div class="form-group col-md-12">
              <label for="address">Address <span class="text-danger">*</span></label>
              <input autocomplete="off" name="address" type="text" class="form-control" id="address" placeholder="" value="{{isset($data) ? $data->address:''}}">
            </div>
            
            <!-- Lat -->
            <div class="form-group col-md-6">
              <label for="lat">Lat <span class="text-danger">*</span></label>
              <input autocomplete="off" name="lat" type="text" class="form-control" id="lat" placeholder="" value="{{isset($data) ? $data->lat:''}}">
            </div>
            
            <!-- Lng -->
            <div class="form-group col-md-6">
              <label for="lng">Lng <span class="text-danger">*</span></label>
              <input autocomplete="off" name="lng" type="text" class="form-control" id="lng" placeholder="" value="{{isset($data) ? $data->lng:''}}">
            </div>
            
            <!-- Distribution Center -->
            <div class="form-group col-md-6">
              <label for="join_at">Distribution Center <span class="text-danger">*</span></label>
              <select data-size=5 data-live-search="true" selectpicker name="distribution_center_id" id="distribution_center_id" class="form-control">
                <option value="">- Pilih -</option>
                @foreach ($dc as $dc_item)
                    <option {{isset($data) && $data->distribution_center_id == $dc_item->id ? 'selected':''}} value="{{$dc_item->id}}">{{$dc_item->name}}</option>
                @endforeach
              </select>
            </div>
            
            <!-- Join At -->
            <div class="form-group col-md-6">
              <label for="join_at">Join At <span class="text-danger">*</span></label>
              <input datepicker autocomplete="off" name="join_at" type="text" class="form-control" id="join_at" placeholder="" value="{{isset($data) ? $data->join_at:''}}">
            </div>

          </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <div class="btn-group">
            <a class="btn btn-secondary" href="{{ route($resource.'.index') }}"><i class="fa fa-arrow-left"></i> Back</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
          </div>
        </div>

      </form>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script src='/theme/plugins/jquery-ui/jquery-ui.min.js'></script>
<script src='{{url('')}}/theme/plugins/bootstrap-select-1.13.9/dist/js/bootstrap-select.min.js'></script>


<script>
//Datepicker
$('[datepicker]').datepicker({dateFormat: 'yy-mm-dd'});
$('[selectpicker]').selectpicker();


</script>
@endpush

@push('styles')
<link rel='stylesheet' href='/theme/plugins/bootstrap-select-1.13.9/dist/css/bootstrap-select.min.css' />

<link rel='stylesheet' href='/theme/plugins/jquery-ui/jquery-ui.min.css' />
<link rel='stylesheet' href='/theme/plugins/jquery-ui/jquery-ui.theme.min.css' />

@endpush
